apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redhat-quay-operator
spec:
  destination:
    name: ''
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  source:
    path: odf-bundle
    repoURL: 'https://github.com/ignaciolago/quay-gitops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true