apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redhat-quay
spec:
  destination:
    name: ''
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  source:
    path: quay-bundle
    repoURL: 'https://github.com/ignaciolago/quay-gitops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PruneLast=true